### ISSUE TITLE
Make "codespeak.net" available as MX domain for mailing lists

### ISSUE THREAD

**Issue by hpk42** [codespeaknet/sysadmin#1]
Currently mailing lists use ``MLNAME@lists.codespeak.net`` and i'd like to rather have ``MLNAME@codespeak.net``. 

currently https://lists.codespeak.net/postorius/domains/new/ offers a mm3 list creation interface. 
What is probably missing is tranfering MX handling for ``codespeak.net`` to the lists machine before we can create a new domain with MM3. 

@fschulze -- as you have read up the most on MM3, is there anything else than transfering MX we need to do before we can "create new domain"?

**Comment by fschulze** [comment]
We should setup postfix first. As far as I can tell so far, we should add ``codespeak.net`` and ``lists.codespeak.net`` explicitly in ``relay_domains`` in addition to the hash lookup on mailman domains that is already there.

Not sure yet about ``transport_maps`` and ``local_recipient_maps``, especially when we also want to add ``autocrypt.org`` (#2). I guess we want separate accounts for that.

After that I can move the lists to codespeak.net.

Then we should setup aliases form lists.codespeak.net, not sure yet where they go.

**Comment by fschulze** [comment]
I guess we only need aliases for the three list adresses, so replying to older mails still works, no need for all the other list admin adresses.

Then some additional tasks:
- [ ] change the etckeeper commit hook address
- [ ] change cron destination (I think root has an alias for that)
- [x] DKIM
- [ ] letsencrypt for certificate

**Comment by fschulze** [comment]
@gfa I noticed you did something in that direction in ``postfix/main.cf``. You should indicate that you do that in here first. I'm now documenting that.

**Comment by fschulze** [comment]
Someone updated DNS to point ``codespeak.net`` to ``lists.codespeak.net`` already.
@hpk the DKIM key that is there is the old existing one, right? So that one needs to be replaced?

**Comment by hpk42** [comment]
i pointed codespeak.net DNS to the VM yesterday.  didn't change DKIM or anything else. sorry, originally i planned to continue but then got drawn away into https://github.com/hpk42/muacrypt hacking land ...

**Comment by fschulze** [comment]
@hpk42 I need to have the website accessible through our server for letsencrypt. I guss for now I can just proxy to the current server at ``94.130.231.157`` for that?

**Comment by gfa** [comment]
@fschulze sorry i just saw this mention

About cron and etckeeper emails, i'd rather send them somewhere else to avoid nasty loops/surprises as we had in the past

**Comment by hpk42** [comment]
there are already now @codespeak.net lists -- so this issue is fixed.
