### ISSUE TITLE
transfer autocrypt.org MX handling

### ISSUE THREAD

**Issue by hpk42** [codespeaknet/sysadmin#2]
see also https://github.com/autocrypt/autocrypt/issues/301

I just checked -- i seem to have an account and can modify DNS for autocrypt.org  https://domains.puscii.nl/domain/autocrypt.org -- i think @fschulze has an account there as well
and maybe others could get one to manage autocrypt dns as well.  For now, just ping me, @fschulze if you need changes (in case of problems we usually need to contact @webmind who originally registered the domain at the autocrypt inauguration meeting in Berlin). 

so the "press-team" alias and the "bot" account needs to be transferred and configured with the VM/postfix after which we can transfer DNS to point to the cs machine. 

MX autocrypt.org needs DKIM keys ( https://github.com/fschulze/shared-admin/blob/master/docs/notes.rst#6-opendkim ). I *think* that the letsencrypt cert we have for autocrypt.org is already usable for postfix.

**Comment by fschulze** [comment]
I'd say ``virtual_mailbox_domains`` is the way to go for this, see http://www.postfix.org/VIRTUAL_README.html

**Comment by hpk42** [comment]
everything is transferred now. thanks everybody.
